enabled: true

damage-entity:
  enabled: true
  default:
    shadow: true
    view-range: 1.0
    view-marge: 16
    background-color:
    see-through: true
    text-format: "-%.2f"
    position: eye
    scale: 0.9, 1.0, 1.1
    move-count: 8
    only-player: true
    animation: 1
    replacement: ""
  apply: damage_cause.yml

regain-health:
  enabled: true
  default:
    shadow: true
    view-range: 1.0
    view-marge: 16
    background-color:
    see-through: false
    text-format: "+%.2f"
    position: foot
    scale: 1
    move-count: 8
    only-player: true
    animation: 2
    replacement: ""
  apply: regain_reason.yml

animation: animation.yml

replacement: replacement_group.yml
