enabled: true

damage-entity:
  enabled: true
  basic:
    shadow: true
    view-range: 1.0
    view-marge: 16
    background-color:
  default:
    text-format: "-%.2f"
    position: eye
    scale: 0.9, 1.0, 1.1
    remove-count: 8
    only-player: true
  critical:
    text-format: "💥%.2f"
    position: damage
    scale: 1.5
    remove-count: 8
    only-player: true
  other: damage_cause.yml


regain-health:
  basic:
    shadow: true
    view-range: 1.0
    view-marge: 16
    background-color:
  default:
    text-format: "+%.2f"
    position: eye
    scale: 1
    remove-count: 8
    only-player: true
  other: regain_reason.yml

animation:
  1:
    mode: up-and-down
    # damage, foot, eye
    from: damage
    y:
      max: 1
      speed: 0.17
  2:
    mode: up
    # foot, eye
    from: foot
    y:
      speed: 0.15

replacement: replacement_group.yml
